[package]
name = "orbital-preview-frontend"
version = "0.1.3"
edition = "2021"
publish = false
license = "MIT"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
orbital = { package = "orbital-ui", path = "../orbital", version = "0.1.3", default-features = false, features = ["hydrate"] }
orbital-preview-app = { path = "../orbital-preview-app", version = "0.1.3", default-features = false }
leptos.workspace = true
console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
wasm-bindgen.workspace = true

[features]
hydrate = [
    "leptos/hydrate",
    "orbital-preview-app/hydrate",
]
