#[cfg(feature = "preview")]
use orbital_core_components::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::products::history::docs::{
        HISTORYDATASOURCEDOC_PREVIEW_REGISTRATION, HISTORYDATEDIVIDERSDOC_PREVIEW_REGISTRATION,
        HISTORYEMBEDDOC_PREVIEW_REGISTRATION, HISTORYFILTERDOC_PREVIEW_REGISTRATION,
        HISTORYGROUPINGDOC_PREVIEW_REGISTRATION, HISTORYHANDLEDOC_PREVIEW_REGISTRATION,
        HISTORYLAYOUTDOC_PREVIEW_REGISTRATION, HISTORYLIVETRANSPORTDOC_PREVIEW_REGISTRATION,
        HISTORYLIVEUPDATEDOC_PREVIEW_REGISTRATION, HISTORYLOADINGDOC_PREVIEW_REGISTRATION,
        HISTORYLOCALIZATIONDOC_PREVIEW_REGISTRATION, HISTORYMARKDOWNDOC_PREVIEW_REGISTRATION,
        HISTORYMULTIDIFFDOC_PREVIEW_REGISTRATION, HISTORYPAGEDDOC_PREVIEW_REGISTRATION,
        HISTORYREFRESHDOC_PREVIEW_REGISTRATION, HISTORYRENDERERSDOC_PREVIEW_REGISTRATION,
        HISTORYSCROLLLOADDOC_PREVIEW_REGISTRATION, HISTORYSERVERFILTERDOC_PREVIEW_REGISTRATION,
        HISTORYSLOTSDOC_PREVIEW_REGISTRATION, HISTORYSORTDOC_PREVIEW_REGISTRATION,
        HISTORYTIMEZONEBUCKETSDOC_PREVIEW_REGISTRATION,
        HISTORYTIMEZONEDISPLAYDOC_PREVIEW_REGISTRATION, HISTORYVIRTUALIZEDDOC_PREVIEW_REGISTRATION,
    };
    use crate::products::history::HISTORYTIMELINE_PREVIEW_REGISTRATION;

    static REGS: &[&PreviewRegistration] = &[
        &HISTORYTIMELINE_PREVIEW_REGISTRATION,
        &HISTORYLAYOUTDOC_PREVIEW_REGISTRATION,
        &HISTORYDATASOURCEDOC_PREVIEW_REGISTRATION,
        &HISTORYLOADINGDOC_PREVIEW_REGISTRATION,
        &HISTORYSLOTSDOC_PREVIEW_REGISTRATION,
        &HISTORYRENDERERSDOC_PREVIEW_REGISTRATION,
        &HISTORYLOCALIZATIONDOC_PREVIEW_REGISTRATION,
        &HISTORYDATEDIVIDERSDOC_PREVIEW_REGISTRATION,
        &HISTORYMULTIDIFFDOC_PREVIEW_REGISTRATION,
        &HISTORYEMBEDDOC_PREVIEW_REGISTRATION,
        &HISTORYHANDLEDOC_PREVIEW_REGISTRATION,
        &HISTORYREFRESHDOC_PREVIEW_REGISTRATION,
        &HISTORYTIMEZONEBUCKETSDOC_PREVIEW_REGISTRATION,
        &HISTORYLIVEUPDATEDOC_PREVIEW_REGISTRATION,
        &HISTORYTIMEZONEDISPLAYDOC_PREVIEW_REGISTRATION,
        &HISTORYFILTERDOC_PREVIEW_REGISTRATION,
        &HISTORYSORTDOC_PREVIEW_REGISTRATION,
        &HISTORYPAGEDDOC_PREVIEW_REGISTRATION,
        &HISTORYSCROLLLOADDOC_PREVIEW_REGISTRATION,
        &HISTORYSERVERFILTERDOC_PREVIEW_REGISTRATION,
        &HISTORYVIRTUALIZEDDOC_PREVIEW_REGISTRATION,
        &HISTORYMARKDOWNDOC_PREVIEW_REGISTRATION,
        &HISTORYLIVETRANSPORTDOC_PREVIEW_REGISTRATION,
        &HISTORYGROUPINGDOC_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static ()] {
    &[]
}
