[package]
name = "orbital-macros"
version = "0.1.5"
edition = "2021"
readme = "README.md"
categories = ["web-programming", "gui"]
keywords = ["leptos", "ui", "wasm", "components", "design-system"]
authors = ["Sean O'Rourke"]
documentation = "https://docs.rs/orbital-macros"
homepage = "https://unified-field-dev.github.io/orbital/"
repository = "https://github.com/unified-field-dev/orbital"
description = "Proc macros for Orbital component documentation and routing helpers"
license = "MIT"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
darling = "0.20"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = false
no-default-features = true
rustdoc-args = ["--cfg", "docsrs"]
